- car.go
LoadCar doesn't use the full `Blockstore` interface, this modifies it to expect less.
> define general Store interface replaces Blockstore

- car.go
This makes it possible to pass in a dagservice "session" for better performance when fetching from bitswap.
> feat: only require the NodeGetter interface instead of the DAG interface

- car/main.go
- car_test.go
- util/util.go
This came up from go-ipfs folks trying to import a CAR file that was truncated but they had no indication that it was. The final block had an `0xa0` after it, which is an improper varint, so `ReadUvarint()` was returning an `io.EOF` which also happens if there's _no_ next block at all and is therefore the proper-EOF signal. This change lifts the proper-EOF case out into a `Peek(1)` so every other EOF from there on can be assumed to be unexpected.
> Improve EOF handling

- car_test.go
- selectivecar.go
This is a simple but pretty obscure feature. When building cars with Selectors, we have an option for a two step write -- one step performs the traversal, while another writes the traversed cids to a file. This is important among other things so that we can get a total file size ahead of time. We also have an option in the 1-step write to call a user defined hook as we write blocks. Now, we allow the two step write to use these user-defined hooks. However, they are not called till you actually dump the file. For a variety of reasons, we need this for Filecoin, but it seems to me to be a non-controversial enough change as to allow us to merge to master?
- hold the user funcs in the intermediate structure
- track offset/size and call during io.Write
> Allow user defined block hooks when using two step write for selective cars

- LICENSE
It looks like this may be confusing pkg.go.dev's license detection.
> chore: remove LICENSE

- .gitignore
- car.go
- car_test.go
Also pulls in #74 and #75
Ref: ipld/js-car#28
> Also included in this is an explicit check for `0aa16776657273696f6e02` (`<length>{version:2}`) as per https://github.com/ipld/specs/pull/248#issuecomment-833141588 so it can be used as a CARv2 escape - if we end up using this string as a modifier for CARv2 we can at least get proper errors out of this if it encounters a newer format.
the primary difference with js-car is that go-car requires a non-empty roots array whereas js-car is fine with empty roots array, hence the test fixture differences
> Header error tests

- .gx/lastpubver
The `.gx` dependency management mechanism seems to date back before go
mod. The folder is untouched for the last 2 years and the repo is using
go mod already.
Removing it now that it is made redundant.
> Remove redundant .gx folder in light of `go.mod`

- v2/doc.go
- v2/go.mod
Note, the entire approach to CAR v2 implementation and package structure is work in progress, hence this PR is against `wip/v2`. For context see https://github.com/ipld/go-car/pull/78#discussion_r648314538
Since we are releasing a new major version, define a new go module for
the CAR v2 implementation, following the recommendations here:
- https://blog.golang.org/v2-go-modules
The module is versioned as go 1.15 to maintain compatibility as pointed
out by comment here:
- https://github.com/ipld/go-car/pull/75#discussion_r644634850
> Define CAR v2 as a separate go module

- v2/blockstore/readonly_test.go
- v2/car.go
- v2/car_test.go
- v2/internal/carbon/carbon.go
- v2/internal/carbon/carbon_fds.go
- v2/internal/carbon/carbon_test.go
- v2/internal/carbs/util/hydrate.go
- v2/internal/index/generator.go
- v2/internal/index/index.go
- v2/internal/io/cid.go
- v2/reader.go
- v2/writer_test.go
Format code in v2 consistently using `gofumpt -l -w .`
> Run `gofumpt -l -w .`

- v2/car.go
- v2/car_test.go
- v2/reader.go
- v2/writer.go
Pragma seems like a better name for the prefix bytes of a car v2. Rename
it along with references to it in tests etc.
It also helps keep the terminology consistent with the [finalising specification](https://github.com/ipld/ipld/pull/107)
> Rename Prefix to Pragma for consistency

- v2/blockstore/readonly.go
- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
- v2/car_test.go
- v2/go.mod
- v2/go.sum
- v2/index/generator.go
- v2/internal/carv1/car.go
- v2/internal/carv1/car_test.go
- v2/internal/carv1/doc.go
- v2/internal/carv1/util/util.go
- v2/internal/carv1/util/util_test.go
- v2/reader.go
- v2/writer.go
Remove dependency to CAR v1 go module, because that module depends on
later version of ipld-prime which have not been reflected in filecoin
project.
In the interest of time, we fork the code that v2 needs in v1. This
allows a more efficient implementation of some APIs that accep types
like `bufio.Reader` while helping the filecoin team push ahead with
deliverables without undergoing a big upgrade process.
On the CAR v2 side, this however means that we postpone the
implementation of Selective Car for v2 until filecoin is upgraded its
ipld-prime dependency. This is to avoid implementing an obsolete
selective car API that uses the old ipld-prime API which force user yet
another upgrade.
> Remove dependency to CAR v1 go module

- v2/blockstore/readwrite.go
- v2/internal/carv1/car.go
- v2/writer.go
We want to simplify the API and not carry over any CAR v1 functionality
we don't have to. We also want to encourage users to use the selective
car functionality to achieve what walk function did once it is added.
> Remove CAR v1 walk function until it is needed

- v2/writer.go
- v2/writer_test.go
Remove the ability to configure index codec in the CAR v2 writer to
avoid unintended complexity, since in the first pass the only supported
codec will be sorted.
> Fix the writer index codec to sorted

- v2/blockstore/doc.go
- v2/blockstore/readonly.go
- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
- v2/index/doc.go
- v2/index/errors.go
- v2/index/generator.go
- v2/index/index.go
- v2/index/insertionindex.go
- v2/internal/carbs/util/hydrate.go
- v2/reader.go
- v2/writer.go
Add documentation where it is sparse to help folks learn how to use the
library easier.
Unexport the ability to select codec, until we decide what codec we want
to expose. Fix all encodings of index to `IndexSorted`.
Fix a bug in writer where index is written by direct marshalling instead
of index.WriteTo which includes index codec.
Refactor in places for better readability.
> Improve documentation and fix bug in writer

- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
- v2/index/insertionindex.go
> blockstore: add option to deduplicate by CID

- v2/blockstore/readonly.go
- v2/go.mod
- v2/index/generator.go
- v2/index/index.go
- v2/internal/carv1/util/util.go
To guarantee minimal encoding.
Fixes #135
> Replace `binary.Put/ReadUvarint` with `go-varint`

- v2/reader.go
- v2/reader_test.go
- v2/testdata/sample-rootless-v42.car
A user has to undergo a lot of boilerplate code to generate or get an
index where there is a CAR file, the version for which is unknown.
Provide a function that accepts either v1 or v2 payload and reads the
index if present, otherwise generates it for the user. The generated
index lives entirely in memory and will not depend on the given
`io.ReadSeeker` to lookup indices.
Implement tests that check index is returned for v1 or v2 files. Add a
sample file with an imaginary version of 42 for testing purposes to
assert that the indexing function will error if the given file is not v1
or v2.
Fixes https://github.com/ipld/go-car/issues/143
> Implement read or generate index from CAR accepting v1 or v2

- v2/blockstore/readonly.go
- v2/blockstore/readonly_test.go
Fix a bug where the returned size in `ReadOnly.GetSize` blockstore was
incorrect and the CID was being read from the wrong offset.
Implement tests to assert returned size matches the block raw data size.
Fixes #133
> Fix bug in ReadOnly blockstore GetSize

- v2/blockstore/readonly_test.go
- v2/blockstore/readwrite.go
Implement tests that check `ReadOnly` blockstore functions work based on
data payload originated from a V1 or V2 formatted CAR file.
Implement tests that assert instantiation of `ReadOnly` blockstore
fails on unexpected pragma version.
> Implement more tests for `ReadOnly` blockstore

- v2/blockstore/insertionindex.go
- v2/blockstore/readwrite.go
- v2/go.mod
- v2/go.sum
- v2/index/errors.go
- v2/index/generator.go
- v2/index/index.go
- v2/index/indexgobhash.go
- v2/index/indexhashed.go
- v2/index/indexsorted.go
Use the codec dedicated to CAR index sorted when marshalling and
unmarshalling `indexSorted`. Note, the code depends on a specific commit
of `go-multicodec` `master` branch. This needs to be replaced with a tag
once a release is made on the go-multicodec side later.
Unexport index APIs that should not be exposed publicly. Remove
`Builder` now that it is not needed anywhere. Move `insertionIndex` into
`blockstore` package since that's the only place it is used.
Introduce an index constructor that takes multicodec code and
instantiates an index.
Fix ignored errors in `indexsorted.go` during marshalling/unmarshlling.
Rename index constructor functions to use consistent terminology; i.e.
`new` instead if `mk`.
Remove redundant TODOs in code.
Relates to:
- …
> Unexport unecesserry index APIs and integrate with mulitcodec

- v2/reader.go
Assume the read seeker passed in is seeked to the beginning of CAR
payload. This is both for consistency of API and avoid unnecessary
seeks when the reader may already be at the right place.
Relates to https://github.com/ipld/go-car/commit/ff72fdd8443ea53256f07dd3acb5d7f7bf665f6f#r53411220
> Remove redundant seek before read or generate index

- v2/blockstore/readwrite.go
- v2/internal/carv1/car.go
- v2/internal/carv1/car_test.go
* Use the file already open to get the stats for resumption purposes. On
getting the stats, because the open flag contains `os.O_CREATE` check 
the size of the file as a way to determine wheter we should attempt 
resumption or not. In practice this is the same as the code that 
explicitly differentiates from non-existing files, since file existence 
doesn't matter here; the key thing is the file content. Plus this also 
avoids unnecessary errors where the files exists but is empty.
* Add TODOs in places to consider enabling deduplication by default and 
optimise computational complexity of roots check. Note, explicitly 
enable deduplication by default in a separate PR so that the change is
clearly communicated to dependant clients in case it causes any
unintended side-effects.
* Rename …
> Address review comments on resumption

- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
Support resumption from a complete CARv2 file, effectively implementing
append block to a CARv2 file. Note, on resumption the entire file is
re-indexed. So it is undesirable to do this for complete cars.
Fix a bug where `AllKeysChan` failed on files that contained the index
and resumed from. Fix is done by truncating the CARv2 file, removing the
index if it is present when blockstore is constructed when resuming.
This is because if `AllKeysChan` is called on a file that contains the
index, the ReadOnly backing will continue to read until EOF which will
result in error. Since file is re-indexed on resumption and we require
finalize to be called we truncate the file to remove index.
Clear out CARv2 header on file if resumed from a finalised file to avoid 
issue where the blocks are put and …
> Support resumption in `ReadWrite` blockstore for finalized files

- v2/blockstore/readonly.go
There's blockstore dependent code in our libraries that depends on this particular error if a block does NOT exist.
> Index error found should return block not found

- v2/blockstore/readonly.go
- v2/blockstore/readwrite.go
- v2/car_test.go
- v2/index/index.go
- v2/index_gen.go
- v2/internal/carv1/car.go
- v2/internal/carv1/util/util.go
- v2/internal/io/converter.go
- v2/reader.go
Remove dependency to `bufio.Reader` in internal `carv1` package that
seems to be mainly used for peeking a byte to return appropriate error
when stream abruptly ends, relating to #36. This allows simplification
of code across the repo and remove all unnecessary wrappings of
`io.Reader` with `bufio.Reader`. This will also aid simplify the
internal IO utilities which will be done in future PRs. For now we
simply remove dependency to `bufio.Reader`.
Relates to:
- https://github.com/ipld/go-car/pull/36
> Remove dependency to `bufio.Reader` in internal `carv1` package

- v2/index_gen.go
- v2/internal/io/converter.go
Implement the ability to generate index from a CARv1 payload given only
an `io.Reader`, where the previous implementation required
`io.ReadSeeker`. The rationale is to be minimal in what we expect in the
API, since index generation from a CARv1 payload never need to rewind
the reader and only moves forward in the stream.
Refactor utility IO functions that convert between types in one place.
Implement constructor functions that only instantiate wrappers when the
passed argument does not satisfy a required interface.
Fixes:
- https://github.com/ipld/go-car/issues/146
Relates to:
- https://github.com/ipld/go-car/issues/145
> Implement index generation using only `io.Reader`

- v2/writer.go
- v2/writer_test.go
Unexport the CARv2 writer API until it is reimplemented using WriterAt
or WriteSeeker to be more efficient. This API is not used anyway and we
can postpone releasing it until SelectiveCar writer API is figured out.
For now we unexport it to carry on with interface finalization and alpha
release.
> Unexport unused `Writer` API until it is re-implemented

- car.go
- car_test.go
- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
- v2/go.mod
- v2/go.sum
- v2/internal/carv1/car.go
- v2/internal/carv1/car_test.go
- v2/writer_test.go
Add tests that assert:
- when padding options are set the payload is as
expected
- when finalized, blockstore calls panic
- when resumed from mismatching padding error is as expected
- when resumed from non-v2 file error is as expected
Remove redundant TODOs in code
> Improve test coverage for `ReadWrite` blockstore

- v2/blockstore/readonly.go
- v2/blockstore/readonly_test.go
- v2/blockstore/readwrite_test.go
- v2/index/indexsorted.go
- v2/index/indexsorted_test.go
Fix an issue where single width index not finding a given key returns
`0` offset instead of `index.ErrNotFound`.
Reflect the changes in blockstore to return appropriate IPFS blockstore
error.
Add tests that asserts error types both in index and blockstore
packages.
Remove redundant TODOs
Relates to:
- #158
> Fix index not found error not being propagated

- v2/index_gen.go
- v2/internal/io/converter.go
Improve reader type conversion by checking if type satisfies
ReaderAt to avoid unnecessary wrapping.
Move io converters into one place.
Fixes:
- https://github.com/ipld/go-car/issues/145
> Refactor utility io conversions into one internal package

- v2/blockstore/readonly_test.go
- v2/index/indexsorted_test.go
- v2/writer.go
- v2/writer_test.go
Remove the memory intensive CARv2 writer implementation since it needs
to be reimplemented anyway and not used. We will release writers if
needed when it comes to SelectiveCar writer implementation. Just now it
is not clear if we want a CARv2 writer that works with the deprecated
`format.NodeGetter`.
Add tests for V1 wrapping functionality.
Reformat code in repo for consistency using `gofumpt`.
> Remove memory intensive writer and add warping tests

- v2/blockstore/doc.go
- v2/blockstore/readonly.go
- v2/blockstore/readonly_test.go
- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
- v2/car.go
- v2/car_test.go
- v2/doc.go
- v2/example_test.go
- v2/index/doc.go
- v2/index_gen.go
- v2/internal/carv1/doc.go
- v2/options.go
- v2/reader.go
- v2/writer.go
- v2/writer_test.go
Rename terminology to match what the spec uses to describe the inner
CARv1 payload, i.e. Data payload.
Update docs to use CARv1 and CARv2 consistently.
Fix typo in Options API.
See:
- https://ipld.io/specs/transport/car/carv2/
> Rename `CarV1` with `Data` in API to be consistent with spec

- v2/blockstore/example_test.go
- v2/blockstore/readwrite_test.go
- v2/example_test.go
- v2/index/example_test.go
Avoid writing to files in `testdata` through examples. This is because
when tests that use those file are run in parallel will fail if files
are modified. Instead write to a temporary file in examples, and
whenever opening testdata files in `RW` mode, make a temporary copy.
Thanks to @mvdan for pointing this out.
Fixes #175
> Avoid writing to files in `testdata`

- v2/index/index_test.go
- v2/index_gen_test.go
When error is not expected in tests, assert that there is indeed no
error.
> Improve error handing in tests

- v2/blockstore/readonly.go
- v2/blockstore/readonly_test.go
- v2/index/index_test.go
- v2/internal/carv1/car.go
- v2/internal/carv1/car_test.go
- v2/internal/carv1/util/util.go
The CARv2 implementation uses an internal fork of CARv1 due to upstream
dependency issues captured in #104. Propagate the options set in CARv2
APIs for treatment of zero-lenth sections onto internal packages so that
APIs using the internal CARv1 reader behave consistently. Use a `bool`
for setting the option, since it is the only option needed in CARv1.
Update tests to reflect changes.
Add additional tests to internal CARv1 package and ReadOnly blockstore
that assert option is propagated.
Fixes #190
> Add zero-length sections as EOF option to internal CARv1 reader

- v2/bench_test.go
- v2/block_reader.go
- v2/block_reader_test.go
- v2/blockstore/bench_test.go
- v2/example_test.go
- v2/reader.go
- v2/reader_test.go
Implement an iterator over CAR blocks that accepts both v1 and v2. The
reader only requires io.Reader interface to operate and exposes the
version and roots of the underlaying CAR file as fields.
Remove `Next` from CARv2 reader now that the iteration functionality is
provided using `BlockReader`.
Update the benchmarks to reflect the changes and add example usage for
`NewBlockReader`.
Add tests that assert `BlockReader` behaviour in erroneous and
successful cases for both underlying CARv1 and CARv2 payload.
> Implement version agnostic streaming CAR block iterator

- README.md
Add examples link to the README and refine its structure.
List features of CARv2.
Use stronger language to encourage users to use `v2` over `v0`.
Relates to #194
> Update the readme with link to examples

- v2/bench_test.go
- v2/writer.go
- v2/writer_test.go
Implement `ExtractV1File` where the function takes path to a CARv2 file
and efficiently extracts its inner CARv1 payload. Note, the
implementation only supports CARv2 as input and returns a dedicated
error if the supplied input is already in CARv1 format.
Implement benchmarks comparing extraction using `Reader` vs
`ExtractV1File`.
Implement tests that assert in-place extraction as well as invalid input
and both v1/v2 input
Fixes #207
> Implement utility to extract CARv1 from a CARv2

- v2/reader_test.go
Write a test that asserts reader instantiated from `OpenReader` do not
panic and instead error gracefully if underlying IO is closed.
Fixes #211
> Assert `OpenReader` from file does not panic after closure

- v2/go.mod
- v2/go.sum
- v2/index/index.go
- v2/index/mhindexsorted.go
- v2/index/mhindexsorted_test.go
- v2/index_gen_test.go
Implement a new CARv2 index that contains enough information to
reconstruct the multihashes of the data payload, since `CarIndexSorted`
only includes multihash digests. The new index builds on top of the 
existing `IndexSorted` by adding an additional layer of grouping the 
multi-width indices by their multihash code.
Note, this index intentionally ignores
any given record with `multihash.IDENTITY` CID hash.
Add a test that asserts offsets for the same CID across sorted index and
new multihash sorted index are consistent.
Add tests that assert marshal unmarshalling of the new index type is as
expected, and it does not load records with `multihash.IDENTITY` digest.
Relates to:
- https://github.com/multiformats/multicodec/pull/227
Fixes https://github.com/ipld/go-car/issues/214
> Implement new index type that also includes mutltihash code

- v2/internal/io/converter.go
(see commit messages - please do not squash)
Using ReadBlocks as an example, we have 30% fewer allocs and 7% less cpu usage.
https://github.com/ipfs/go-cid/pull/132 does another 11% and 3%, respectively.
> stop allocating on every byte read (for CIDs and varints)

- v2/index/index.go
- v2/index/indexsorted.go
- v2/index/mhindexsorted.go
- v2/index_gen_test.go
Implement API that allows iteration over multihashes and offsets in
`MultihasIndexSorted`. The API is specific to this index type;
therefore, the type is now exported along with its constructor funtion.
Write test that asserts `GetAll` and `ForEach` behave consistently.
Relates to #95
> Expose the ability to iterate over records in `MultihasIndexSorted`

- v2/index/indexsorted.go
- v2/index/indexsorted_test.go
Refine `GetAll` logic so that it stops iteration if either function
returns false or there are no more entries to search.
Fixes #216
> Fix index GetAll infinite loop if function always returns `true`

- v2/cmd/car/car.go
- v2/cmd/car/detach.go
- v2/cmd/car/filter.go
- v2/cmd/car/list.go
example usage:
```
car list test.car | head -n 50 | car filter test.car trimmed.car
```
> Add `list` and `filter` commands

- v2/cmd/car/index.go
When running `car index` from a v1 file, the wrong data length was being used for the wrapped v2 header.
> use file size when loading from v1 car

- v2/blockstore/doc.go
- v2/blockstore/readonly_test.go
- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
- v2/car.go
- v2/car_test.go
- v2/errors.go
- v2/errors_test.go
- v2/index/index.go
- v2/index/indexsorted.go
- v2/index/indexsorted_test.go
- v2/index/mhindexsorted.go
- v2/index/mhindexsorted_test.go
- v2/index_gen.go
- v2/options.go
- v2/options_test.go
Implement two additional options that allow a CARv2 file to 1) include
IDENTNTIY CIDs, and 2) specify a maximum allowed CID length with default
of 2KiB as a sufficiently large default.
Configure ReadWrite blockstore to persist given blocks with IDENTITY
CIDs.
Introduce a new Characteristics filed that signalls whether an index in
a CAR file contains a full catalog of CIDs for backward compatibility
purposes. Note, this is a new addition and will need to be added to the
spec in a separate PR.
Relates to #215
> Implement options to handle `IDENTITY` CIDs gracefully

- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
> blockstore: OpenReadWrite should not modify if it refuses to resume

- v2/writer.go
- v2/writer_test.go
Implement an API that allows a caller to replace root CIDs in an
existing CAR file, may it be v1 or v2, as long as the resulting
serialized header is of identical size to the existing header.
Assert that the new API works in a variety of CARv1 and CARv2 files
along with failure scenarios.
Fixes #245
> Implement API to allow replacing root CIDs in a CARv1 or CARv2

- car_test.go
- go.mod
- go.sum
- options.go
- options_test.go
- selectivecar.go
- selectivecar_test.go
Expose `Options` for `NewSelectiveCar()` for two new features available in go-ipld-prime:
1. `traversal.LinkVisitOnlyOnce` which I've called `TraverseLinksOnlyOnce` here - defaulting to `false`
2. `traversal.Budget#LinkBudget` which I've called `MaxTraversalLinks` here - defaulting to _disabled_
I've gone with the same `Options` pattern as in v2 and taken @masih's advice here to keep it generic (rather than use `SelectiveCarOptions`) so the same pattern can be used for the non-selective CAR usage functions. We'll just have to be clear about what options apply to what functions I suppose.
I've put `Traverse` in both option names for this reason - to try and make it clear that they are for selector traversal. But, in the future we could retire the merkledag `Walk` use here and replace it …
> Expose selector traversal options for SelectiveCar

- go.mod
- go.sum
Will tag a v0.3.2 after merging this (https://github.com/ipld/go-car/releases/tag/untagged-af0ba029227dcfe003d9)
> chore: update go-ipld-prime dependency

- cmd/car/car.go
- cmd/car/get.go
- cmd/car/index.go
I was just noticing in #246 that `get-dag` doesn't seem quite right so went about trying to address it, then in the process I'm realising that I don't have much use for CARv2 with much of the stuff I'm interested in and not having the option to make v1 CARs is a bit annoying, so I added a `-version` to it as well.
The current form seems to write out every matching _node_ in a selector, not _block_, which will get pretty gnarly with complex blocks and a match-all and likely not what the user wants. This version uses the selector for the walk only (so it can be an explore, not a match) and uses the block loader to indicate what blocks are visited. It's not entirely unreasonable that a user may want to match individual nodes and turn them into blocks, but I think it's very unlikely desired …
> feat: fix get-dag and add version=1 option

- v2/blockstore/readonly.go
- v2/blockstore/readonly_test.go
The blockstore reads the version of the given CAR payload to determine
whether to generate an index for the given payload or not. When the
payload represents a CARv1 and no index is specified, the backing reader
is passed on for index generation. But the version is already read from
the stream. Seek to the beginning of the backing reader before
generating the index so that the index generation mechanism receives the
complete CARv1.
Fixes #265
> Seek to start before index generation in `ReadOnly` blockstore

- cmd/car/extract.go
If the root of a car is a unixfs file, without the containing directory entry, we can still extract it, we just don't have a filename for it.
> Allow extracton of a raw unixfs file

- cmd/car/car.go
- cmd/car/create.go
- cmd/car/extract.go
- cmd/car/get.go
- cmd/go.mod
- cmd/go.sum
* `car ls` as an alias for `car list`
* Update to newer `unixfsnode`
> Car command supports for `largebytes` nodes

- v2/reader.go
- v2/reader_test.go
Instead of fully reading the index, only peak the index codec until
streaming index read is implemented. This would offer a safer
`Inspect()` call but with the tradeoff that overflow in index size is no
longer detected. Hence the tests that are now removed.
> Only read index codec during inspection

- v2/blockstore/readwrite.go
This allow the caller to control the file lifecycle and implement a cleaning strategy. An example would be:
- open a file in a temporary folder
- if the write suceed, close the file and move it to its final destination
- on error, remove the file
If the underlying filesystem support it, an anonymous file can be used instead: open then immediately delete, use the file descriptor to write. A crash before the end of the write process would release the used storage automatically.
Not a breaking change, only introduce an extra function.
> blockstore: allow to pass a file to write in

- v2/blockstore/readwrite_test.go
Address https://github.com/ipld/go-car/pull/323#issuecomment-1200823708
> OpenReadWriteFile: add test

- v2/internal/io/skip_writer_read_seeker.go
- v2/internal/loader/writing_loader.go
- v2/selective.go
I pulled out my review suggestions from #291 into a commit here for separate (and hopefully easier) review. Mostly just code comments that I thought would be useful for the next person walking through the code, plus a couple of renames.
> fix: minor doc fixes, updates and improvements from review

- .github/workflows/go-check.yml
- .github/workflows/go-test.yml
- cmd/go.mod
- cmd/go.sum
- fuzz_test.go
- go.mod
- v2/blockstore/doc.go
- v2/blockstore/example_test.go
- v2/blockstore/readonly_test.go
- v2/blockstore/readwrite_test.go
- v2/example_test.go
- v2/fuzz_test.go
- v2/go.mod
- v2/index/doc.go
- v2/index/example_test.go
- v2/internal/carv1/car.go
- v2/internal/io/converter.go
- v2/internal/loader/writing_loader.go
- v2/reader.go
- v2/selective.go
- v2/writer_test.go
- version.json
(pr to #330)
and bumps version to 0.5.0 when merged
> fix: remove use of ioutil

- v2/blockstore/readonly.go
- v2/blockstore/readonly_test.go
- v2/index_gen.go
- v2/options.go
When StoreIdentityCIDs is set, it will defer to the index to check whether the
blocks are in the CAR. When the CAR is a v1 and StoreIdentityCIDs is set, the
index will contain the identity CIDs. When it's a v2 with an existing index,
however that index was created will determine whether the identity CIDs are
that are in the CAR are found.
When StoreIdentityCIDs is not set, Has() will always return true and Get() will
always return the block.
---
The background to this is trying to get identity CID retrievals properly working in Lotus _and_ trying to emulate the `car.SelectiveCar` CAR creation when using the RW blockstore to back a Graphsync transfer. Currently, a Lotus client will use `car.SelectiveCar` to make the CAR for the deal to calculate CommP. Then it'll transfer the CAR to the …
> feat: Has() and Get() will respect StoreIdentityCIDs option

- v2/block_reader.go
- v2/block_reader_test.go
- v2/internal/carv1/util/util.go
> add a `SkipNext` method on block reader

- cmd/car/car.go
- cmd/car/compile.go
- cmd/car/testdata/script/compile.txt
- cmd/go.mod
This change adds two new sub-commands to the car CLI
car debug file.car
creates a patch-file-compatible representation of the content of the car file. Blocks will be represented in dag-json pretty-printed form.
car compile file.patch
will do the inverse process of building a car file from a debug patch file. CIDs will be re-compiled based on the contents of blocks, with links in parent blocks updated to point to the compiled values.
an example debug patch of the car used in the testscript test fixture would be:
```patch
car compile --v2 small.car
root bafybeidx5vxxny6ca3mgs5d6wy5ubwcibpirctmktpkvfk4io34i2ww2hy
for raw: bytes are 68656c6c6f20776f726c640a
--- bafkreifjjcie6lypi6ny7amxnfftagclbuxndqonfipmb64f2km2devei4
+++ raw bafkreifjjcie6lypi6ny7amxnfftagclbuxndqonfipmb64f2km2devei4
@@ …
```
> Add a debugging form for car files.

- car.go
Pass through the `merkledag.WalkOption` parameters to the underlying `merkledag.Walk()` function.
This is helpful for a number of use-cases, in particular it allows creating a CAR with missing nodes. E.g., currently it's not possible to create a CAR with raw links pointing to CIDs not present in the local blockstore. After this change, you can use the following:
```golang
car.WriteCar(ctx, dagService, []cid.Cid{root.Cid()}, carFile, merkledag.IgnoreErrors())
```
> Allow using WalkOption in WriteCar function

- .github/workflows/release-binaries.yml
- .gitignore
- .goreleaser.yaml
Closes: https://github.com/ipld/go-car/issues/354
> feat: add release-binaries workflow

- cmd/car/car.go
- cmd/car/index.go
- cmd/car/testdata/script/index-create.txt
Ran into a case where I had a large CARv1 and wanted to create an index from it so I could use the two as a CARv2 blockstore (trying to take a 120GB ~69M block CARv1 of Filecoin state and use it as a blockstore for queries). IIUC this separation of the CARv1 from the index is common in Lotus/Boost and is part of why there's already a `detach` command.
First time contributing to this CLI so lmk if there's a better way you had in mind, or a better place to put this command. We may also want an `index attach` command at some point, but that can be a separate PR.
If people are happy with this, I can add a basic test for this as well (once I figure out the syntax of the test framework).
> feat(cmd): add index create subcommand to create an external carv2 index

- cmd/go.mod
- cmd/go.sum
- v2/storage/doc.go
Crossing my fingers and attempting to fix the new flaky macos CI failures for testing the cmd package. I can replicate it locally after enough test re-runs and haven't been able to replicate it with this update, but it's flaky so that doesn't prove anything.
@mvdan are you aware of anything that might be coming out of testscript that's causing flaky CI executions on macos-only? We see them pretty regularly now, e.g.:
* https://github.com/ipld/go-car/actions/runs/4042032455/jobs/6949254029
* https://github.com/ipld/go-car/actions/runs/4042175271/jobs/6949563292
* https://github.com/ipld/go-car/actions/runs/4120011819/jobs/7114311099
* https://github.com/ipld/go-car/actions/runs/4045723899/jobs/6957586152
They all have the pattern:
```
[signal: killed]
FAIL: testdata/script/root.txt:1: …
```
> deps(cmd): update go-internal dependency

- v2/blockstore/readwrite.go
- v2/internal/store/insertionindex.go
Note: I'm not entirely sure I didn't break some assumption.
close https://github.com/ipld/go-car/issues/242
Crude benchmark:
```
func BenchmarkAllKeysChan(b *testing.B) {
path := filepath.Join(b.TempDir(), "bench-large-v2.car")
generateRandomCarV2File(b, path, 10<<20) // 10 MiB
defer os.Remove(path)
bs, err := blockstore.OpenReadWrite(path, nil)
if err != nil {
b.Fatal(err)
}
b.ReportAllocs()
b.ResetTimer()
for i := 0; i < b.N; i++ {
c, err := bs.AllKeysChan(context.Background())
if err != nil {
b.Fatal(err)
}
for range c {
}
}
}
```
Before:
> BenchmarkAllKeysChan-12    	     772	   2022389 ns/op	   89049 B/op	    1617 allocs/op
After
> BenchmarkAllKeysChan-12    	    8824	    195779 ns/op	   30865 B/op	     642 allocs/op
10.3X faster, allocate 2.5X less memory.
> blockstore: fast path for AllKeysChan using the index

- v2/block_reader.go
- v2/block_reader_test.go
- v2/options.go
Attempt to make CAR traversal a little bit faster by not forcing users to hash every single block in a CAR.
> Add WithTrustedCar() reader option

- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
The goal being to be able to keep reading blocks and the index after safely finalizing the file on disk. Typically for indexing purpose.
More tests are likely required, but PR for early feedback.
fix #375
> ReadWrite: add an alternative FinalizeReadOnly+Close flow

- v2/blockstore/readwrite.go
- v2/index/index.go
- v2/internal/store/insertionindex.go
- v2/internal/store/put.go
Before:
`BenchmarkHas-12            205046            6404 ns/op            744 B/op            16 allocs/op`
After
`BenchmarkHas-12            2354449            481.3 ns/op            160 B/op            3 allocs/op`
```
func BenchmarkHas(b *testing.B) {
ctx := context.TODO()
path := filepath.Join(b.TempDir(), "bench-large-v2.car")
generateRandomCarV2File(b, path, 200<<20) // 10 MiB
defer os.Remove(path)
subject, err := blockstore.OpenReadWrite(path, nil)
c, err := subject.AllKeysChan(ctx)
require.NoError(b, err)
var allCids []cid.Cid
for c2 := range c {
allCids = append(allCids, c2)
}
b.ReportAllocs()
b.ResetTimer()
var idx int
for i := 0; i < b.N; i++ {
_, _ = subject.Has(ctx, allCids[idx])
// require.NoError(b, err)
// require.True(b, has)
idx = (idx + 1) % len(allCids)
}
}
```
> ReadWrite: faster Has() by using the in-memory index instead of reading on disk

- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
- v2/internal/store/indexcheck.go
- v2/storage/storage.go
- v2/storage/storage_test.go
I realised too late that #393 didn't have the whole CID vs multihash differentiation in its new Has() that it needs to have. So adding it back in here and giving the same fast-path treatment to the storage API that blockstore has from #393.
> fix: handle (and test) WholeCID vs not; fast Has() path for storage

- v2/blockstore/readonly.go
- v2/blockstore/readonly_test.go
- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
- v2/index/index.go
This can be useful for advanced read-only operation, like indexing.
> blockstore: give a direct access to the index for read operations

- v2/blockstore/readwrite.go
- v2/index/insertionindex.go
- v2/internal/store/index.go
- v2/internal/store/indexcheck.go
- v2/internal/store/resume.go
- v2/storage/storage.go
> refactor insertion index to be publicly accessible

- cmd/car/extract.go
- cmd/car/testdata/script/create-extract.txt
otherwise results in a blocking wait when you do an extract-all but there are missing blocks that you're waiting for a "done" signal for.
> fix: reading from stdin should broadcast EOF to block loaders

- car.go
- car_test.go
This accounted for almost 10% of the garbage on one of Bluesky's server daemons (go tool pprof --alloc_space), leading to high GC CPU.
benchstat:
│   before    │                after                │
│   sec/op    │   sec/op     vs base                │
NewCarReader_small-8   2.005µ ± 1%   1.451µ ± 5%  -27.61% (p=0.000 n=10)
│    before    │                after                 │
│     B/op     │     B/op      vs base                │
NewCarReader_small-8   5.268Ki ± 0%   1.135Ki ± 0%  -78.46% (p=0.000 n=10)
│   before   │               after               │
│ allocs/op  │ allocs/op   vs base               │
NewCarReader_small-8   29.00 ± 0%   27.00 ± 0%  -6.90% (p=0.000 n=10)
> perf: reduce NewCarReader allocations

- v2/storage/storage.go
- v2/storage/storage_test.go
Mirrors https://github.com/ipld/go-car/pull/387 but for v2/storage instead of v2/blockstore; since we don't have an `AllKeysChan` equivalent, I think this is probably the simplest path to exposing simple "iterate-all", and even a fast "has" functionality. I've already been making use of this exposed index.
> feat: expose index for StorageCar

- cmd/car/car.go
- cmd/car/create.go
This was something I found that could be useful when creating CARs. Let me know what you think. I created a negative flag since the default is to wrap, not changing the default.
> feat(cmd/car): add '--no-wrap' option to 'create' command

- cmd/car/car.go
- cmd/car/filter.go
Adds the options `--version` and `--inverse` to `car filter` so that:
```sh
echo $REMOVED_CID | car filter --version 1 --inverse ./input.car ./output.car
```
Removes the CID and outputs a carv1.
Context:
- `--inverse` is useful to filter out a CID out of a car, related: https://github.com/ipfs/gateway-conformance/issues/75
- `--version` is required to workaround https://github.com/ipfs/kubo/issues/9361
> feat: add inverse and version to filter cmd

- car.go
- car_test.go
Allow reading a car even when roots is empty
> fix: opt-in way to allow empty list of roots in CAR headers

- version.json
Adds support for a v1 car reader that is okay with an empty `roots` array in the header.
> v0.6.2 bump

- v2/block_reader.go
- v2/block_reader_test.go
* SkipNext's metadata calculation wasn't working properly in the case of a CARv2 as it didn't take into account the V1 header in the original offset calculation.
* Add a SourceOffset and some docs to be absolutely clear what offsets we're returning in the metadata.
Ref: https://github.com/filecoin-project/boost/pull/1651
> feat: fix BlockReader#SkipNext & add SourceOffset property

- v2/storage/deferred/deferredcarwriter.go
- v2/storage/deferred/deferredcarwriter_test.go
- v2/storage/storage.go
Extracted from Lassie; removed the default CARv1 option from the `NewDeferredCarWriterForPath` variant, but left it on for `NewDeferredCarWriterForStream`. Also had to wire up `Close` to `Finalize` to handle the CARv2 case (and added tests to cover the CARv2 case).
> feat: add DeferredCarWriter

- v2/block_reader.go
- v2/block_reader_test.go
@willscott while the CARv2 offsets were completely broken prior to #491 and I made it match for both CARv1 and CARv2; I changed the meaning of "Offset" in the process, making it the data offset, not section offset. Unfortunately because there were no tests or docs in there the intention wasn't clear so I made an assumption. I just discovered this after updating go-car in vanilla Boost and getting the section read errors ("bad cid version").
So this is a bugfix, to change it back to section offset but also make both CARv1 and CARv2 work (+ docs + tests).
> fix: BlockMetadata#Offset should be for section, not block data

- cmd/car/car.go
- cmd/car/list.go
Output looks like, e.g. 
```
bafy... foo.txt
```
Resolve the remaining ask in https://github.com/ipld/go-car/issues/335#issuecomment-1877248159
> Add a `car ls --unixfs-blocks` to render two-column output

- cmd/car/extract.go
- cmd/car/filter.go
- cmd/car/get.go
- cmd/car/inspect.go
- cmd/car/lib/extract.go
- cmd/car/lib/filter.go
- cmd/car/lib/inspect.go
- cmd/car/lib/root.go
- cmd/car/lib/verify.go
- cmd/car/root.go
- cmd/car/verify.go
Address all but `list` as requested in #523 
@lordshashank  - list seems to be really focused on a bunch of different textual printed output - i'm not really sure what a library variant of it would be vs what's already provided in the main carv2 library interface - can you specify if there's something specific you're after there?
> Re-factor cmd functions to library

- cmd/car/filter.go
- cmd/car/testdata/script/filter.txt
I guess I'm the first person to actually want to use these.
> fix(cmd): properly pick up --inverse and --cid-file args

- v2/go.mod
- v2/go.sum
Discovered that this is really annoying when go-car/v2 is a dependency because it forces every downstream to also have the specific version and toolchain.
Came in via https://go-review.googlesource.com/c/exp/+/611956, just a dep upgrade over there, not missing out on anything, this rolls back to the previous version.
> chore: downgrade golang.org/x/exp to avoid specific go versioning

- .github/workflows/release-binaries.yml
- .goreleaser.yaml
Ref: https://github.com/ipld/go-car/issues/536
(a small amount of 🤞 going on here, we'll see, this works for lassie)
> fix: goreleaser v2 compat, trigger release-binaries with workflow_run

- cmd/go.mod
- go.mod
- v2/go.mod
This reverts commit 76b9ce47ee9c75907298eab3029c22d05dd824e7.
Putting back 1.23 support while we get #603 in.
> Revert "ci: uci/update-go (#602)"
