ipld/go-car

- car.go
> don't use private types in public functions

- car_test.go
Should fix the go-check failure in https://github.com/ipld/go-car/pull/41/checks.
> run gofmt -s

- LICENSE
- LICENSE-APACHE
- LICENSE-MIT
- README.md
All copyrightable contributions were made by PL employees anyways.
> chore: relicense

- v2/car.go
- v2/car_test.go
- v2/carbs/carbs_test.go
- v2/go.mod
- v2/offset_reader.go
- v2/reader.go
- v2/writer.go
Provide an API to read sections of a CAR v2 as well as a utility to get a `Blockstore` from a CAR v2.
> Implement CAR v2 Reader

- v2/internal/index/indexsorted.go
Note specs need to be update to reflect this here:
- https://github.com/ipld/ipld/pull/107
For context, see:
- https://github.com/ipld/ipld/pull/107/files#r656749263
> Use unsigned integer to represent width and count in sorted index

- v2/reader.go
Change the `ReadPragma` signature to only return the version and drop
the roots that _may_ exist if the version is 1. Because, this results in
a less error-prone API, and right now it is unclear if we want
functionality that should return roots. So, we lean towards providing
less functionality unless requested.
> Rename `ReadPragma` to `ReadVersion` and drop returning roots

- v2/LICENSE.md
This will allow pkgsite to render the wip-v2 module.
> copy v1 license into the v2 module

- v2/index/index.go
Also add TODOs about cleaning up the API. We can't do that right now, as
it would require a refactor in the other packages.
> index: use the IndexSorted multicodec

- v2/blockstore/readonly.go
- v2/reader.go
@mvdan @masih 
- It's nice to be able to open blockstores/CARv2 Readers with just the CARv2 file paths. 
- The blockstores should have a close method that closes the backing CARv2 file.
> add Close methods and NewReaderMmap

- v2/blockstore/readonly.go
- v2/blockstore/readwrite_test.go
> blockstore: close AllKeysChan channel when done

- v2/blockstore/readonly.go
- v2/blockstore/readwrite.go
> blockstore: make unsupported methods panic

- v2/blockstore/readonly.go
- v2/blockstore/readwrite_test.go
> consistently use CID hashes for uniqueness

- v2/blockstore/readonly.go
- v2/blockstore/readwrite_test.go
- v2/index/errors.go
- v2/index/indexgobhash.go
- v2/index/indexhashed.go
- v2/index/indexsorted.go
- v2/index/insertionindex.go
> blockstore: don't error on Has not finding a CID

- v2/blockstore/readonly.go
- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
> blockstore: make it safe for concurrent use

- v2/internal/carv1/util/util.go
> replace util.ReadCid with go-cid

- v2/reader.go
> avoid exposing io.SectionReader in the API

- v2/example_test.go
- v2/index/generator.go
- v2/internal/carbs/util/hydrate.go
- v2/writer.go
> add carv2.WrapV1 based on io interfaces

- v2/blockstore/readonly.go
- v2/blockstore/readwrite_test.go
- v2/index/generator.go
> index: add support for null paddings in Generate

- v2/go.mod
- v2/go.sum
> use the now-merged cid.CidFromReader

- v2/blockstore/doc.go
- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
- v2/example_test.go
- v2/reader.go
> make all "Open" APIs use consistent names

- v2/go.mod
- v2/go.sum
> update go-cid to get the CidFromReader panic fix

- v2/blockstore/readonly.go
- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
- v2/index_gen.go
- v2/options.go
- v2/reader.go
> unify options and add more blockstore options

- v2/blockstore/readonly.go
- v2/blockstore/readonly_test.go
Implement a mechanism that allows the user to hook an error handling
function to the context passed to `AllKeysChan`. The function is then
notified when an error occurs during asynchronous traversal of data
payload.
Add tests that assert the success and failure cases when error handler
is set.
Fixes #177
> Propagate async `blockstore.AllKeysChan` errors via context

- v2/bench_test.go
- v2/blockstore/bench_test.go
> add the first read-only benchmarks

- v2/blockstore/example_test.go
- v2/blockstore/export_test.go
- v2/blockstore/readwrite.go
- v2/blockstore/readwrite_test.go
> blockstore: stop embedding ReadOnly in ReadWrite

- LICENSE.md
> re-add root LICENSE file

- LICENSE.md
- v2/LICENSE.md
> update LICENSE files to point to the new gateway

- v2/options.go
> clarify the relation between StoreIdentityCIDs and SetFullyIndexed

- version.json
> Update `version.json` after manual tag push

- cmd/car/car.go
- cmd/car/detach.go
> add `car detach-index list` to list detached index contents

- v2/internal/io/skip_writer_read_seeker.go
Boost needs to be able to cancel an active writer cleanly. It's currently possible by calling a `Seek()` but the next `Read()` will just start it up again.
> feat: make SkipWriterReaderSeeker an io.Closer

- README.md
- cmd/car/README.md
Hopefully this addresses some of the comments from the bedrock meeting
> cleanup readme a bit to make the cli more discoverable

- v2/blockstore/readwrite.go
OpenReadWriteFile gives full control of the file to the caller, so it should not decide to close the file, even on error.
> blockstore: only close the file on error in OpenReadWrite, not OpenReadWriteFile

- cmd/car/car.go
- cmd/car/concat.go
Usage:
`car concat a.car b.car ... > combined.car`
> Add a concatination cli utility
